#!/bin/bash
tmp=$(mktemp -d)
#tmp="../Paper_temp"
#mkdir $tmp
mkdir "$tmp"/Paper
echo 'TEMP Folder:' $tmp;
cp * "$tmp"/Paper -R
rm "$tmp"/Paper/CreateInstaller
rm "$tmp"/Paper/README.md
rm "$tmp"/Paper/protected/config/User_config.php
rm "$tmp"/Paper/assets/* -r
rm "$tmp"/Paper/protected/GTemplates/* -r
rm "$tmp"/Paper/protected/GBlocks/* -r
find "$tmp"/Paper -name ".gitignore" -exec rm -rf {} \;
chmod a+rw "$tmp"/Paper/*
tar -czvf Paper_installer.tar.gz -C "$tmp" Paper
rm "$tmp" -r
